import { Post, Tag, Author } from './types';

export const mockTags: Tag[] = [
  { id: 't1', name: 'React', count: 0 },
  { id: 't2', name: 'TypeScript', count: 0 },
  { id: 't3', name: 'Game', count: 0 },
  { id: 't4', name: 'Triết học', count: 0 },
  { id: 't5', name: 'Flutter', count: 0 },
  { id: 't6', name: 'Mobile Development', count: 0 },
  { id: 't7', name: 'DevOps', count: 0 },
  { id: 't8', name: 'Docker', count: 0 },
  { id: 't9', name: 'Kinh tế', count: 0 },
  { id: 't10', name: 'Esports', count: 0 },
  { id: 't11', name: 'JavaScript', count: 0 },
  { id: 't12', name: 'Web Development', count: 0 },
  { id: 't13', name: 'UI/UX', count: 0 },
  { id: 't14', name: 'Design', count: 0 },
];

export const mockPosts: Post[] = [
	{
		id: 'p1',
		title: 'Tối ưu hóa Component trong React với TypeScript',
		slug: 'toi-uu-hoa-react-typescript',
		summary: 'Cách sử dụng generics và memoization để tăng hiệu năng ứng dụng React.',
		content:
			'<h3>1. Giới thiệu</h3><p>React và TypeScript là sự kết hợp hoàn hảo.</p><h3>2. Kỹ thuật</h3><p>Sử dụng <b>React.memo</b> và <b>useMemo</b> để tối ưu render.</p>',
		avatarUrl: 'https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png',
		author: 'Trần Nguyên',
		createdAt: '2026-04-15',
		views: 1250,
		status: 'Đã đăng',
		tags: ['React', 'TypeScript'],
	},
	{
		id: 'p2',
		title: 'Phân tích cơ chế Gacha và Pity trong Genshin Impact',
		slug: 'phan-tich-gacha-genshin',
		summary: 'Phân tích xác suất toán học đằng sau hệ thống banner của Genshin Impact.',
		content:
			'<h3>Hệ thống Pity</h3><p>Thông thường, bạn được đảm bảo nhận nhân vật 5 sao ở lần roll thứ 90. Tuy nhiên, <i>Soft Pity</i> bắt đầu từ roll 74.</p>',
		avatarUrl: 'https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png',
		author: 'Trần Nguyên',
		createdAt: '2026-04-20',
		views: 342,
		status: 'Đã đăng',
		tags: ['Game'],
	},
	{
		id: 'p3',
		title: 'Vai trò của Kinh tế Chính trị Mác - Lênin',
		slug: 'kinh-te-chinh-tri-mac-lenin',
		summary: 'Tóm tắt các điểm chính về giá trị thặng dư và ứng dụng lý luận thực tiễn.',
		content:
			'<p>Kinh tế chính trị Mác - Lênin nghiên cứu quan hệ sản xuất trong sự tác động qua lại với lực lượng sản xuất và kiến trúc thượng tầng.</p>',
		avatarUrl: 'https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png',
		author: 'Trần Nguyên',
		createdAt: '2026-03-10',
		views: 890,
		status: 'Đã đăng',
		tags: ['Triết học'],
	},
	{
		id: 'p4',
		title: 'Cấu trúc thư viện và Clean Architecture trong Flutter',
		slug: 'clean-architecture-flutter',
		summary: 'Hướng dẫn tổ chức dự án Flutter theo kiến trúc phân lớp để dễ dàng bảo trì và mở rộng.',
		content:
			'<h3>1. Các lớp kiến trúc</h3><p>Chia dự án thành 3 lớp chính: <b>Data</b>, <b>Domain</b>, và <b>Presentation</b>.</p><h3>2. Lợi ích</h3><p>Giúp tách biệt logic nghiệp vụ khỏi giao diện và framework.</p>',
		avatarUrl: 'https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png',
		author: 'Trần Nguyên',
		createdAt: '2026-04-21',
		views: 450,
		status: 'Đã đăng',
		tags: ['Flutter', 'Mobile Development'],
	},
	{
		id: 'p5',
		title: 'Ứng dụng Docker trong quy trình CI/CD',
		slug: 'docker-cicd-workflow',
		summary: 'Cách container hóa ứng dụng để đảm bảo tính đồng nhất giữa các môi trường phát triển.',
		content:
			'<h3>Khái niệm Containerization</h3><p>Docker giúp đóng gói mã nguồn và tất cả các phụ thuộc vào một <i>Image</i> duy nhất.</p><h3>Triển khai</h3><p>Sử dụng Docker Compose để quản lý đa dịch vụ trong môi trường staging.</p>',
		avatarUrl: 'https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png',
		author: 'Trần Nguyên',
		createdAt: '2026-04-22',
		views: 210,
		status: 'Đã đăng',
		tags: ['DevOps', 'Docker'],
	},
	{
		id: 'p6',
		title: 'Phân tích Quy luật Giá trị trong nền Kinh tế Thị trường',
		slug: 'quy-luat-gia-tri-kinh-te',
		summary: 'Vai trò điều tiết sản xuất và lưu thông hàng hóa của quy luật giá trị.',
		content:
			'<p>Quy luật giá trị yêu cầu việc sản xuất và trao đổi hàng hóa phải dựa trên cơ sở <b>hao phí lao động xã hội cần thiết</b>.</p><p>Nó thúc đẩy cải tiến kỹ thuật và phân hóa những người sản xuất hàng hóa.</p>',
		avatarUrl: 'https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png',
		author: 'Trần Nguyên',
		createdAt: '2026-03-15',
		views: 670,
		status: 'Đã đăng',
		tags: ['Kinh tế', 'Triết học'],
	},
	{
		id: 'p7',
		title: 'Chiến thuật xây dựng đội hình trong Teamfight Tactics (TFT)',
		slug: 'chien-thuat-tft-mua-moi',
		summary: 'Cách quản lý lợi tức và chọn lõi công nghệ để tối ưu hóa thứ hạng.',
		content:
			'<h3>1. Quản lý lợi tức</h3><p>Giữ mức 50 vàng để tối đa hóa lượng lợi tức nhận được mỗi vòng.</p><h3>2. Lựa chọn lõi</h3><p>Ưu tiên các lõi cung cấp chỉ số sức mạnh toàn diện cho đội hình <i>Flex</i>.</p>',
		avatarUrl: 'https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png',
		author: 'Trần Nguyên',
		createdAt: '2026-04-18',
		views: 1580,
		status: 'Đã đăng',
		tags: ['Game', 'Esports'],
	},
	{
		id: 'p8',
		title: 'Xử lý bất đồng bộ trong JavaScript với Async/Await',
		slug: 'async-await-javascript',
		summary: 'Cú pháp hiện đại giúp mã nguồn sạch hơn so với sử dụng Callback hay Promises truyền thống.',
		content:
			'<h3>Cú pháp</h3><p>Sử dụng từ khóa <b>async</b> trước hàm và <b>await</b> trước một Promise.</p><h3>Xử lý lỗi</h3><p>Kết hợp với khối <i>try...catch</i> để kiểm soát các ngoại lệ một cách chặt chẽ.</p>',
		avatarUrl: 'https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png',
		author: 'Trần Nguyên',
		createdAt: '2026-04-10',
		views: 920,
		status: 'Đã đăng',
		tags: ['JavaScript', 'Web Development'],
	},
	{
		id: 'p9',
		title: 'Tâm lý học hành vi trong thiết kế giao diện (UI/UX)',
		slug: 'tam-ly-hoc-ui-ux',
		summary: 'Ứng dụng các quy luật tâm lý như Định luật Fitts và Hiệu ứng Von Restorff vào thiết kế.',
		content:
			'<p>Thiết kế không chỉ là thẩm mỹ mà còn là khoa học về cách con người tương tác với hệ thống.</p><ul><li><b>Định luật Hick:</b> Thời gian đưa ra quyết định tăng theo số lượng lựa chọn.</li><li><b>Sự tập trung:</b> Sử dụng khoảng trắng để dẫn dắt thị giác.</li></ul>',
		avatarUrl: 'https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png',
		author: 'Trần Nguyên',
		createdAt: '2026-04-05',
		views: 1100,
		status: 'Đã đăng',
		tags: ['UI/UX', 'Design'],
	},
];

export const mockAuthor: Author = {
	name: 'Trần Nguyên',
	avatar: require('./avt/End_Gateway.gif'),
	bio: 'Sinh viên chuyên ngành Công nghệ Thông tin tại PTIT. Đam mê lập trình Front-end, nghiên cứu lịch sử và các hệ thống quân sự chiến lược.',
	skills: ['React', 'TypeScript', 'Ant Design', 'Tư duy logic', 'Phân tích hệ thống'],
	socialLinks: [
		{ label: 'GitHub', url: 'https://github.com' },
		{ label: 'LinkedIn', url: 'https://linkedin.com' },
	],
};
